import 'package:flutter/material.dart';

// Colors
const cTransparent = Colors.transparent;
const cGreen = Colors.green;
const cGreenAccent = Colors.greenAccent;
const cBlue = Colors.blue;
const cPurple = Colors.purple;
const cWhite = Colors.white;
const cYellow = Colors.yellow;
const cOrange = Colors.orange;
const cBlack = Colors.black;
const cGrey = Colors.grey;
const cRed = Colors.red;
const cPink = Colors.pink;
const cBlueGrey = Colors.blueGrey;
const cAmber = Colors.amber;
const cBrown = Colors.brown;
const cCyan = Colors.cyan;
const cIndigo = Colors.indigo;
const cLime = Colors.lime;
const cTeal = Colors.teal;
const cDeepPurple = Colors.deepPurple;
const cDeepOrange = Colors.deepOrange;
const cRedAccent = Colors.redAccent;
const cIndigoAccent = Colors.indigoAccent;
const cLightBlue = Colors.lightBlue;
const cLightGreen = Colors.lightGreen;
const cAmberAccent = Colors.amberAccent;
const cBlueAccent = Colors.blueAccent;
const cPinkAccent = Colors.pinkAccent;
